### ISSUE TITLE
When deployment/service is deleted, after n hrs gateway listener is removed and never re-added

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-api-gateway#230]
### Overview of the Issue

I have an HTTPRoute that points at two services. When I delete the services the listener is still configured on the gateway. After a certain time (12h?), Kubernetes triggers a re-resolve on the HTTPRoute and it's determined that the route is invalid since it targets non-running services, this causes the listener to be deleted.

If I then restart my services, the listener isn't added back. I have to restart the api gateway controller to get the listener back.

**Comment by andrewstucki** [comment]
For some context, this happens because we're not properly re-reconciling routes when their `backendRef` services are deleted. When the service is deleted in Consul, all of its config entries get cleaned up, so there's still a listener, but it has no valid upstream rules (seems kind of odd that you can get Consul in this state, since you normally can't register a listener with 0 upstreams, though it seems you can register with 1 upstream, and then delete it).

After the 12h(?) period, Kubernetes triggers periodic reconciliation that sees we now have an invalid `backendRef` and removes the listener because it has no valid upstream rules (since Consul doesn't allow us to register a listener with no upstreams).

The restart of the services doesn't do anything for re-reconciling/updating the gateway config entries b/c of the lack of a service watch, but restarting the controller works because it causes the gateways/routes to re-reconcile yet again.

Fix should be to set up route reconciliations based off of upstream service lifecycle events -- we'll need to additionally add in some care to avoid race-conditions in our dirty checking code for our resolved gateway state.

Additionally, I have the feeling that a similar bug could happen in the presence of networking issues that cause a gateway to be de-registered as a service -- that the underlying config entries could be deleted automatically by Consul without us realizing we need to re-create them, so our fix should look into doing periodic re-syncs of all of our gateway state.

**Comment by nathancoleman** [comment]
Thanks guys! I'll get started on a fix for this today. As discussed, it won't make our v0.3.0 release next week, but we can cut a patch release if necessary once the fix is merged.

**Comment by nathancoleman** [comment]
Update here: I've got a working fix for this that I'll have up for code review on Monday
