### ISSUE TITLE
Tight loop spamming config entry delete errors after deleting gateway

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-api-gateway#82]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Reproduction Steps

1. Followed learn guide (https://learn-git-consul-er-api-gw-hashicorp.vercel.app/tutorials/consul/kubernetes-api-gateway)
2. Then deleted the gateway: `k delete gateway test-gateway`

3. Controller is now spamming:

```
2022-01-27T22:20:02.013Z [WARN]  gatewayclient/middleware.go:39: consul-api-gateway-server.k8s.Gateway: received non-Kubernetes error, delaying requeue:
  error=
  | error removing service defaults config entries: 1 error occurred:
  | 	* Unexpected response code: 500 (rpc error making call: service "test-gateway-merged-9b9265b" has protocol "tcp", which does not match defined listener protocol "http")
  |
```

**Comment by andrewstucki** [comment]
@lkysow Thanks for the issue, looks like we have a problem with our ordering of our cleanup operations when a gateway we're deleting has bound routes.

Looks like we need to re-order these operations to remove the ingress that references the corresponding route prior to removing its `service-defaults`. Otherwise, attempting to delete the `service-defaults` first causes the said error because the `ingress-gateway` config entry now references a virtual service which now has the wrong, default `tcp`, protocol when it's specified in the listener as `http`:

https://github.com/hashicorp/consul-api-gateway/blob/967d09d3173727ce4e2f30f0420e0baf8c0d449e/internal/adapters/consul/sync.go#L294-L306

For now, the way to get the gateway to delete properly is to clean up the routes bound to it prior to issuing the gateway delete command. So, in the tutorial: `kubectl delete -f api-gw/routes.yaml` should allow the gateway to be deleted and the spammed errors to stop.
